-- DROP DATABASE
DROP DATABASE IF EXISTS ecommerce_db;

-- CREATE DATABASE
CREATE DATABASE ecommerce_db;

USE ecommerce_db;

CREATE TABLE Category(
    id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    category_name VARCHAR(30) NOT NULL
);

CREATE TABLE Product(
    id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    product_name VARCHAR(30) NOT NULL,
    price DECIMAL(10,2) NOT NULL,
    stock INTEGER NOT NULL DEFAULT 10,
    category_id INTEGER,
    FOREIGN KEY (category_id) REFERENCES Category(id) ON DELETE SET NULL,
);

CREATE TABLE Tag(
    id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    tag_name VARCHAR(30)
);

CREATE TABLE ProductTag(
    id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
    product_id INTEGER,
    FOREIGN KEY (product_id) REFERENCES Product(id) ON DELETE SET NULL,
    tag_id INTEGER,
    FOREIGN KEY (tag_id) REFERENCES Tag(id) ON DELETE SET NULL
);